---
title: "Read fixed file format"
author: "Abraham. G. Habtai"
date: "16 oktober 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message= FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Obligatory assignment 5 -working with child birth data
```{r}
getwd()
rm(list=ls())
library(readr)
library(tidyverse)
library(mosaic)
```
##Importing data through"read_fwf""
```{r}
birth_data2017<-read_fwf(file = "Nat2014PublicUS.c20150514.r20151022.txt",
         fwf_positions(start = c(13,475,504),
                       end = c(14,475,507),
                       col_names = c("month","gender","weight")))

```
##view & changing class
```{r}

str(birth_data2017)
head(birth_data2017)
birth_data2017$month <- as.numeric(birth_data2017$month)
birth_data2017$gender<-as.factor(birth_data2017$gender)
birth_data2017$weight<-as.numeric(birth_data2017$weight)

tail(birth_data2017)
length(birth_data2017$weight)
```

##Cleaning data

```{r}
#removing the data that seems false 
birth_data2017%>% summarise(sum(birth_data2017$weight == 9999))
birth_data<- birth_data2017 %>% filter(weight < 9999)
glimpse(birth_data)
str(birth_data)
head(birth_data,10)
```

## working with data
```{r}
summary(birth_data)
names(birth_data)
mean(birth_data$weight)
favstats(birth_data$weight)
favstats(birth_data$month)
favstats(~weight|month, data = birth_data)
summary(lm(weight~as.factor(month), data = birth_data))
```

#tally boys & grils
```{r}
tally(birth_data$gender)
tally(birth_data$gender, format = "percent")
```
#mean weight
```{r}
favstats(birth_data$weight)
```

##graphs
```{r}
library(tidyverse)
ggplot(birth_data,aes(x=weight))+geom_density()+
  labs(title="density of birth")
favstats(birth_data$weight)
ggplot()+geom_density(data= birth_data, aes(x=weight, group=gender, 
  fill =gender),alpha=0.5,adjust=2)+
  labs(title= "Weight at birth")+
  xlab("Birth Weight")+ ylab("Density")


       
```


